spring:
  application:
    name: taskapp

  profiles:
    active: dev

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    org.hibernate.SQL: debug